env:
  browser: true
  es2021: true
  react-native/react-native: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-native
rules: 
    react/react-in-jsx-scope: off
    react/prop-types: off
    react/jsx-closing-tag-location: error
